### ISSUE TITLE
charmap error code

### ISSUE THREAD

**Issue by vaccarieli** [connor-makowski/srt-translator#5]
Hello I am getting this error.. can u please help .

Traceback (most recent call last):
  File "C:\Users\elios\Desktop\srt-translator\run.py", line 25, in <module>
    results=Translate(input_filepath=file_to_translate,
  File "C:\Users\elios\Desktop\srt-translator\code\translate.py", line 8, in Translate
    aggregate_sentences_dict=AggregateSentences(in_file)
  File "C:\Users\elios\Desktop\srt-translator\code\helpers.py", line 16, in AggregateSentences
    for line in in_file:
  File "C:\Users\elios\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 670: character maps to <undefined>

**Comment by connor-makowski** [comment]
Oops, looks like I am just now seeing this. My apologies there. The package has been updated multiple times since this was posted, so I hope this is now resolved. Closing it now. Feel free to reopen if it is still an issue with the newer package.
